# Generated by Django 3.1 on 2021-01-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmgenre',
            table='djfilmgenre',
        ),
        migrations.AlterModelTable(
            name='filmperson',
            table='djfilmperson',
        ),
        migrations.AlterModelTable(
            name='filmtype',
            table='djfilmtype',
        ),
        migrations.AlterModelTable(
            name='filmwork',
            table='djfilmwork',
        ),
        migrations.AlterModelTable(
            name='filmworkgenre',
            table='djfilmworkgenre',
        ),
        migrations.AlterModelTable(
            name='filmworkperson',
            table='djfilmworkperson',
        ),
    ]
