version: '3'
services:
  postgrescinema:
    image: postgres:13
    restart: unless-stopped
    container_name: cinemaDB
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/production:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    networks:
      - cinema_net
  djangocinema:
    restart: unless-stopped
    container_name: cinemaDjango
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgrescinema
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=$POSTGRES_SCHEMA
      - DJANGO_HOST=$DJANGO_HOST
      - DJANGO_PORT=$DJANGO_PORT
      - DJANGO_SECRET=$DJANGO_SECRET
    build: ./cinema_admin/
    command: /docker-entrypoint.sh
    volumes:
      - web-static:/cinema_admin/config/static
    networks: 
      - cinema_net
    depends_on:
      - postgrescinema
  nginxcinema:
    restart: unless-stopped
    container_name: cinemaNginx
    environment:
      - DJANGO_SERVICE_NAME=djangocinema
      - DJANGO_PORT=$DJANGO_PORT
    build: ./nginx/
    volumes: 
      - web-static:/usr/share/nginx/html/static:ro
    ports:
      - $NGINX_HTTP_PORT:80
    networks: 
      - cinema_net
    depends_on:
      - djangocinema
  etlcinema:
    restart: 'no'
    container_name: cinemaETL
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgrescinema
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=$POSTGRES_SCHEMA
    build: ./etl/
    volumes:
      - dump-db:/etl/db
    networks:
      - cinema_net
    depends_on:
      - postgrescinema
  rediscinema:
    restart: unless-stopped
    container_name: cinemaRedis
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_PORT=$REDIS_PORT
    ports:
      - 127.0.0.1:6379:$REDIS_PORT
    build: ./redis/
    volumes:
      - ./redis/production:/data
    networks:
      - cinema_net
volumes:
  web-static:
  dump-db:
networks:
  cinema_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24     
