version: '3'
services:
  postgrescinema:
    image: postgres:13
    restart: unless-stopped
    container_name: cinemaDB
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/production:/var/lib/postgresql/data
    ports:
      - $POSTGRES_PORT:5432
    networks:
      - cinema_net
  djangocinema:
    restart: unless-stopped
    container_name: cinemaDjango
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST=postgrescinema #Как-то надо передать имя хоста докера
      - POSTGRES_PORT=5432 #Потому-что соединение происходит внутри сети cinema_net
      - POSTGRES_SCHEMA=$POSTGRES_SCHEMA
      - DJANGO_HOST=$DJANGO_HOST
      - DJANGO_PORT=$DJANGO_PORT
    build: ./cinema_admin
    command: ./manage.py runserver 0.0.0.0:$DJANGO_PORT
    ports:
      - $DJANGO_PORT:$DJANGO_PORT
    networks: 
      - cinema_net
    depends_on:
      - postgrescinema
networks:
  cinema_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24     
